name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:   
    - uses: actions/checkout@v2
    - name: Fetch all history for all tags and branches
      run: git fetch --prune --unshallow
    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0.9.2
      with:
          versionSpec: '5.2.x'
    - name: Use GitVersion
      uses: gittools/actions/gitversion/execute@v0.9.2
      id: gitversion 
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag stavocha/react-app:${{ steps.gitversion.outputs.semVer }}
    - name: Login to GitHub Docker Registry
      run: docker login docker.io --username $DOCKER_USERNAME --password $DOCKER_PASSWORD
      env:
        DOCKER_USERNAME: ${{ secrets.REPO_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.REPO_PASS }}
    - name: Push docker image to registry
      run: docker push stavocha/react-app:${{ steps.gitversion.outputs.semVer }}
    outputs:
      version: ${{ steps.gitversion.outputs.semVer }}
    
  deploy:
    runs-on: ubuntu-latest 
    needs: ["build"] 
    steps:
    - name: Deploy to Docker Compose
      uses: wshihadeh/docker-deployment-action@v1
      with:
        remote_docker_host: ubuntu@13.59.245.80
        ssh_private_key: ${{ secrets.DOCKER_SSH_PRIVATE_KEY }}
        ssh_public_key: ${{ secrets.DOCKER_SSH_PUBLIC_KEY }}
        deployment_mode: docker-compose
        copy_stack_file: true
        deploy_path: ~/my-deployment
        stack_file_name: docker-compose.yaml
        keep_files: 5
        pull_images_first: true
      env:
        TAG: ${{needs.build.outputs.version}}

