name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag stavocha/react-app:$GITHUB_RUN_NUMBER
    - name: Login to GitHub Docker Registry
      run: docker login docker.pkg.github.com --username $DOCKER_USERNAME --password $DOCKER_PASSWORD
      env:
        DOCKER_USERNAME: ${{ secrets.REPO_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.REPO_PASS }}
    - name: Push docker image to registry
      run: docker push stavocha/react-app:$GITHUB_RUN_NUMBER

