name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Set tag value
      run: tag = $(date +%s)
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag stavocha/react-app:$tag
    - name: Push docker image to registry
      run: docker push stavocha/react-app:$tag

